### ISSUE TITLE
Freezes game upon pressing copy

### ISSUE THREAD

**Issue by Aktimoose** [mishpro-programm/infoinpause#2]
Clicking the copy button on any level will freeze the game (not a normal crash so no crashlog, game will just hang and not respond)

Version
v1.1.0

Geode Version
v2.0.0beta23

Platform
Windows, Android (crash happens on both)

**Comment by mishpro-programm** [comment]
Fixed it in v1.1.1. Hope it'll be accepted soon

**Comment by mishpro-programm** [comment]
Oh already accepted
